# Generated by Django 5.0.3 on 2026-04-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horoscoperesult',
            name='interpretation_text',
        ),
    ]
