# Generated by Django 5.0.3 on 2026-05-01 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_profiles_public(apps, schema_editor):
    HoroscopeProfile = apps.get_model("chart", "HoroscopeProfile")
    HoroscopeProfile.objects.all().update(is_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_horoscopeprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopeprofile',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='horoscopeprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            set_existing_profiles_public,
            migrations.RunPython.noop,
        ),
    ]
