# Generated by Django 5.0.3 on 2026-05-01 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_horoscopeprofile_is_public_horoscopeprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscoperesult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horoscoperesult',
            name='cache_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='horoscoperesult',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('cache_key',), name='unique_public_chart_result_cache_key'),
        ),
        migrations.AddConstraint(
            model_name='horoscoperesult',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'cache_key'), name='unique_private_chart_result_user_cache_key'),
        ),
    ]
