# Generated by Django 5.0.3 on 2026-05-07 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_horoscoperesult_user_alter_horoscoperesult_cache_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('deck_type', models.CharField(choices=[('tarot', 'Tarot'), ('oracle', 'Oracle')], default='tarot', max_length=20)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('allow_reversed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarot_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_system', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('arcana', models.CharField(choices=[('major', 'Major Arcana'), ('minor', 'Minor Arcana'), ('oracle', 'Oracle')], max_length=20)),
                ('suit', models.CharField(blank=True, choices=[('none', 'None'), ('cups', 'Cups'), ('pentacles', 'Pentacles'), ('swords', 'Swords'), ('wands', 'Wands')], default='none', max_length=20)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('upright_meaning', models.TextField()),
                ('reversed_meaning', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tarot_cards/%Y/%m/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarot_cards', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='chart.tarotdeck')),
            ],
            options={
                'ordering': ['deck_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TarotReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_type', models.CharField(choices=[('one_card', 'One Card'), ('three_card', 'Three Card'), ('custom', 'Custom')], default='one_card', max_length=20)),
                ('question', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='chart.tarotdeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarot_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TarotReadingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('position_label', models.CharField(blank=True, max_length=80)),
                ('is_reversed', models.BooleanField(default=False)),
                ('card_name_snapshot', models.CharField(max_length=120)),
                ('meaning_snapshot', models.TextField()),
                ('image_snapshot', models.CharField(blank=True, max_length=500)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_cards', to='chart.tarotcard')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='chart.tarotreading')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='tarotdeck',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('slug',), name='unique_system_tarot_deck_slug'),
        ),
        migrations.AddConstraint(
            model_name='tarotreadingcard',
            constraint=models.UniqueConstraint(fields=('reading', 'position'), name='unique_tarot_reading_card_position'),
        ),
    ]
