# Generated by Django 5.0.3 on 2026-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_tarotdeck_tarotcard_tarotreading_tarotreadingcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotreading',
            name='ai_interpretation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
