# Generated by Django 5.0.3 on 2026-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_tarotreading_ai_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotreading',
            name='ai_interpretation',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
    ]
