# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0008_alter_tarotreading_ai_interpretation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarotdeck",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
