# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chart", "0009_tarotdeck_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarotdeck",
            name="is_public",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
