# Generated by Django 5.0.3 on 2026-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_alter_tarotdeck_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotdeck',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='tarot_decks/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tarotdeck',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
