# Generated by Django 5.0.3 on 2026-04-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_diaryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, default='profile_icons/logo.png', upload_to='profile_icons/'),
        ),
    ]
