# Generated by Django 5.0.3 on 2026-05-09 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_alter_profile_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryMemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('source_date', models.DateField()),
                ('source_title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_chunks', to='diaryapp.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_memory_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_date', 'chunk_index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='diarymemorychunk',
            constraint=models.UniqueConstraint(fields=('diary', 'chunk_index'), name='unique_diary_memory_chunk_index'),
        ),
    ]
